blank_issues_enabled: true
contact_links:
  - name: Open-ended discussion
    url: https://github.com/legal-ontologies-foundry/legal-ontologies-foundry.github.io/discussions
    about: Ideas and questions that are not yet concrete proposals
