#!/usr/bin/env python3
"""Build the Foundry registry from ontology/*.md (OBO Foundry style).

Each ontology/{id}.md has YAML front matter (metadata) and a Markdown body
(long description). This script:

  1. validates every entry against util/schema/registry_schema.json,
  2. checks cross-entry rules (unique ids/prefixes, known dependencies),
  3. writes docs/registry/index.md and docs/ontologies/{id}.md,
  4. writes docs/registry/ontologies.yml and ontologies.jsonld,
  5. writes build/w3id/lof/.htaccess for the w3id.org pull request.

Never edit the generated files; edit ontology/{id}.md instead.
"""
from pathlib import Path
import json
import re
import sys

import yaml
from jsonschema import Draft202012Validator

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "ontology"
SCHEMA = ROOT / "util" / "schema" / "registry_schema.json"
DOCS = ROOT / "docs"
REG_DIR = DOCS / "registry"
ONT_DIR = DOCS / "ontologies"
W3ID_DIR = ROOT / "build" / "w3id" / "lof"

BASE = "https://w3id.org/lof"
EXTERNAL = {
    "bfo": ("Basic Formal Ontology", "https://basic-formal-ontology.org/"),
    "ro": ("Relation Ontology", "https://oborel.github.io/"),
    "iao": ("Information Artifact Ontology", "https://github.com/information-artifact-ontology/IAO"),
    "cco": ("Common Core Ontologies", "https://github.com/CommonCoreOntology/CommonCoreOntologies"),
}
GENERATED = "<!-- GENERATED by scripts/build_registry.py. Edit ontology/{id}.md instead. -->"


def load_site_url() -> str:
    cfg = yaml.safe_load((ROOT / "mkdocs.yml").read_text(encoding="utf-8"))
    return cfg["site_url"].rstrip("/")


def parse(path: Path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not m:
        raise ValueError(f"{path.name}: missing YAML front matter")
    return yaml.safe_load(m.group(1)), m.group(2).strip()


def repo_parts(url: str):
    org, repo = url.rstrip("/").split("/")[-2:]
    return org, repo


def products(e):
    i = e["id"]
    return [
        ("Full release", f"{BASE}/{i}.owl"),
        ("Base release", f"{BASE}/{i}/{i}-base.owl"),
    ]


def detail_page(e, body):
    i = e["id"]
    rows = [
        ("ID", f"`{i}`"),
        ("Prefix", f"`{e['preferred_prefix']}`"),
        ("Term IRI pattern", f"`{BASE}/{e['preferred_prefix']}_nnnnnnn`"),
        ("Domain", e["domain"]),
        ("Jurisdictions", ", ".join(e["jurisdictions"])),
        ("Status", f"{e['status']} ({e['activity_status']})"),
        ("Repository", f"<{e['repository']}>"),
        ("Issue tracker", f"<{e['tracker']}>"),
        ("License", f"[{e['license']['label']}]({e['license']['url']})"),
        ("Contact", f"{e['contact']['label']} ({e['contact']['email']})"),
    ]
    if e.get("replaced_by"):
        rows.append(("Replaced by", f"[{e['replaced_by']}]({e['replaced_by']}.md)"))
    if e.get("review"):
        rows.append(("Review", f"{e['review'].get('date', '')} {e['review'].get('issue', '')}".strip()))
    out = [GENERATED.format(id=i), "", f"# {e['title']}", "", e["description"], "",
           "| | |", "|---|---|"]
    out += [f"| **{k}** | {v} |" for k, v in rows]
    out += ["", "## Products", "", "| Product | IRI |", "|---|---|"]
    out += [f"| {t} | <{u}> |" for t, u in products(e)]
    deps = e.get("dependencies") or []
    if deps:
        out += ["", "## Dependencies", ""]
        for d in deps:
            if d["id"] in EXTERNAL:
                name, url = EXTERNAL[d["id"]]
                out.append(f"- [{name}]({url})")
            else:
                out.append(f"- [{d['id']}]({d['id']}.md)")
    if e.get("usages"):
        out += ["", "## Usages", ""]
        out += [f"- {u['description']}" + (f" (<{u['url']}>)" if u.get("url") else "") for u in e["usages"]]
    if e.get("publications"):
        out += ["", "## Publications", ""]
        out += [f"- {p['title']} (<{p['id']}>)" for p in e["publications"]]
    if body:
        out += ["", "## Description", "", body]
    return "\n".join(out) + "\n"


def htaccess(entries, site_url):
    L = [
        "# Legal Ontologies Foundry (LOF) persistent identifiers",
        "# GENERATED by scripts/build_registry.py from the Foundry registry.",
        "# Do not edit by hand; regenerate and resubmit.",
        f"# Registry: {site_url}/registry/",
        "",
        "Options +FollowSymLinks",
        "RewriteEngine on",
        "",
        "# Machine-readable registry",
        f"RewriteRule ^registry/ontologies\\.(yml|jsonld)$ {site_url}/registry/ontologies.$1 [R=302,L]",
        "",
    ]
    for e in sorted(entries, key=lambda x: x["id"]):
        i, pfx = e["id"], e["preferred_prefix"]
        org, repo = repo_parts(e["repository"])
        br = e.get("branch", "main")
        raw = f"https://raw.githubusercontent.com/{org}/{repo}"
        q = i  # ids are [a-z0-9-] per schema; no regex metacharacters
        L += [
            f"# ---- {i} ({pfx}) ----",
            f"RewriteRule ^{q}\\.owl$ {raw}/{br}/lof-{i}.owl [R=302,L]",
            f"RewriteRule ^{q}/{q}-base\\.owl$ {raw}/{br}/lof-{i}-base.owl [R=302,L]",
            f"RewriteRule ^{q}/releases/([^/]+)/{q}\\.owl$ {raw}/v$1/lof-{i}.owl [R=302,L]",
            f"RewriteRule ^{q}/releases/([^/]+)/{q}-base\\.owl$ {raw}/v$1/lof-{i}-base.owl [R=302,L]",
            f"RewriteRule ^{q}/imports/(.+)$ {raw}/{br}/src/ontology/imports/$1 [R=302,L]",
            f"RewriteRule ^{q}/tracker$ {e['tracker']} [R=302,L]",
            f"RewriteRule ^{q}/home$ {e.get('homepage', e['repository'])} [R=302,L]",
            f"RewriteRule ^{pfx}_([0-9]{{7}})$ {site_url}/ontologies/{i}/ [R=302,L]",
            "",
        ]
    L += ["# Everything else: the Foundry website",
          f"RewriteRule ^(.*)$ {site_url}/$1 [R=302,L]", ""]
    return "\n".join(L)


def main() -> None:
    validator = Draft202012Validator(json.loads(SCHEMA.read_text(encoding="utf-8")))
    site_url = load_site_url()
    entries, bodies, errors = [], {}, []

    for path in sorted(SRC.glob("*.md")):
        try:
            meta, body = parse(path)
        except Exception as exc:  # noqa: BLE001
            errors.append(str(exc))
            continue
        for err in validator.iter_errors(meta):
            loc = "/".join(str(p) for p in err.absolute_path) or "(root)"
            errors.append(f"{path.name}: {loc}: {err.message}")
        if meta.get("id") != path.stem:
            errors.append(f"{path.name}: id '{meta.get('id')}' must match file name")
        entries.append(meta)
        bodies[meta.get("id")] = body

    ids = [e.get("id") for e in entries]
    prefixes = [e.get("preferred_prefix") for e in entries]
    for dup in {x for x in ids if ids.count(x) > 1}:
        errors.append(f"duplicate id: {dup}")
    for dup in {x for x in prefixes if prefixes.count(x) > 1}:
        errors.append(f"duplicate prefix: {dup}")
    known = set(ids) | set(EXTERNAL)
    for e in entries:
        for d in e.get("dependencies") or []:
            if d["id"] not in known:
                errors.append(f"{e.get('id')}: unknown dependency '{d['id']}'")
        if e.get("status") == "deprecated" and e.get("replaced_by") and e["replaced_by"] not in ids:
            errors.append(f"{e.get('id')}: replaced_by '{e['replaced_by']}' not in registry")

    if errors:
        print("Registry validation failed:", *errors, sep="\n  ", file=sys.stderr)
        sys.exit(1)

    REG_DIR.mkdir(parents=True, exist_ok=True)
    ONT_DIR.mkdir(parents=True, exist_ok=True)
    W3ID_DIR.mkdir(parents=True, exist_ok=True)
    for old in ONT_DIR.glob("*.md"):
        old.unlink()

    rows = [
        GENERATED.format(id="*"), "", "# Registry", "",
        "Ontologies and design patterns registered with the Foundry. "
        "Status values are defined in the [metadata policy](../policy/metadata.md). "
        "Machine-readable versions: [ontologies.yml](ontologies.yml), "
        "[ontologies.jsonld](ontologies.jsonld).", "",
        "| ID | Title | Prefix | Jurisdictions | Status | Activity |",
        "|---|---|---|---|---|---|",
    ]
    for e in sorted(entries, key=lambda x: x["id"]):
        rows.append(
            f"| [`{e['id']}`](../ontologies/{e['id']}.md) | {e['title']} | `{e['preferred_prefix']}` "
            f"| {', '.join(e['jurisdictions'])} | {e['status']} | {e['activity_status']} |"
        )
    rows += ["", "To register an ontology, follow the "
             "[new ontology request SOP](../sop/new-ontology-request.md).", ""]
    (REG_DIR / "index.md").write_text("\n".join(rows), encoding="utf-8")

    for e in entries:
        (ONT_DIR / f"{e['id']}.md").write_text(detail_page(e, bodies[e["id"]]), encoding="utf-8")

    full = []
    for e in sorted(entries, key=lambda x: x["id"]):
        d = dict(e)
        d["products"] = [{"title": t, "iri": u} for t, u in products(e)]
        d["term_iri_prefix"] = f"{BASE}/{e['preferred_prefix']}_"
        full.append(d)
    (REG_DIR / "ontologies.yml").write_text(
        yaml.safe_dump({"ontologies": full}, sort_keys=False, allow_unicode=True), encoding="utf-8")
    jsonld = {
        "@context": {
            "@vocab": f"{BASE}/registry/",
            "id": "@id",
            "title": "http://purl.org/dc/terms/title",
            "description": "http://purl.org/dc/terms/description",
            "repository": {"@id": "http://usefulinc.com/ns/doap#repository", "@type": "@id"},
        },
        "ontologies": [dict(o, id=f"{BASE}/{o['id']}.owl", registry_id=o["id"]) for o in full],
    }
    (REG_DIR / "ontologies.jsonld").write_text(json.dumps(jsonld, indent=2), encoding="utf-8")
    (W3ID_DIR / ".htaccess").write_text(htaccess(entries, site_url), encoding="utf-8")
    print(f"Registry OK: {len(entries)} entries; wrote registry, detail pages, and w3id .htaccess")


if __name__ == "__main__":
    main()
